"""Type stubs for lexindex."""

from collections.abc import Iterator
from typing import final

__all__ = ["CompactHashIndex", "PerfectHashIndex", "StringIndex", "__version__"]

__version__: str

@final
class StringIndex:
    """Ordered string<->id index (FST) with prefix / range / fuzzy / subsequence queries."""

    def __new__(cls, items: list[str]) -> StringIndex: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str, /) -> bool: ...
    def is_empty(self) -> bool: ...
    def id(self, key: str) -> int | None: ...
    def contains(self, key: str) -> bool: ...
    def key(self, id: int) -> str | None: ...
    def ids_of(self, keys: list[str]) -> list[int | None]: ...
    def keys_of(self, ids: list[int]) -> list[str | None]: ...
    def prefix(self, prefix: str, limit: int | None = None) -> list[tuple[str, int]]: ...
    def range(self, lo: str, hi: str, limit: int | None = None) -> list[tuple[str, int]]: ...
    def successor(self, query: str) -> tuple[str, int] | None: ...
    def predecessor(self, query: str) -> tuple[str, int] | None: ...
    def fuzzy(
        self, query: str, max_distance: int, limit: int | None = None
    ) -> list[tuple[str, int]]: ...
    def subsequence(self, query: str, limit: int | None = None) -> list[tuple[str, int]]: ...
    def __iter__(self) -> Iterator[tuple[str, int]]: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> StringIndex: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> StringIndex: ...
    @staticmethod
    def load_mmap(path: str) -> StringIndex: ...

@final
class PerfectHashIndex:
    """Minimal-perfect-hash dictionary: fastest exact string->dense id, with persistence."""

    def __new__(cls, items: list[str]) -> PerfectHashIndex: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str, /) -> bool: ...
    def is_empty(self) -> bool: ...
    def id(self, key: str) -> int | None: ...
    def id_unchecked(self, key: str) -> int: ...
    def contains(self, key: str) -> bool: ...
    def key(self, id: int) -> str | None: ...
    def ids_of(self, keys: list[str]) -> list[int | None]: ...
    def keys_of(self, ids: list[int]) -> list[str | None]: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> PerfectHashIndex: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> PerfectHashIndex: ...
    @staticmethod
    def load_mmap(path: str) -> PerfectHashIndex: ...

@final
class CompactHashIndex:
    """Smallest string->dense id map: minimal perfect hash + per-key fingerprints.

    Membership is probabilistic (false-positive rate ``2 ** -fingerprint_bits``) and there is no
    reverse ``id -> key``. Use it when only ``string -> id`` is needed and size is paramount.
    """

    def __new__(
        cls,
        items: list[str],
        fingerprint_bytes: int = 1,
        *,
        fingerprint_bits: int | None = None,
    ) -> CompactHashIndex: ...
    @property
    def fingerprint_bits(self) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str, /) -> bool: ...
    def is_empty(self) -> bool: ...
    def id(self, key: str) -> int | None: ...
    def id_unchecked(self, key: str) -> int: ...
    def contains(self, key: str) -> bool: ...
    def ids_of(self, keys: list[str]) -> list[int | None]: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> CompactHashIndex: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> CompactHashIndex: ...
    @staticmethod
    def load_mmap(path: str) -> CompactHashIndex: ...
