"""Type stubs for betula-index."""

from typing import final

__all__ = ["PerfectHashIndex", "StringIndex"]

@final
class StringIndex:
    """Ordered string<->id index (FST) with prefix / range / fuzzy / subsequence queries."""

    def __new__(cls, items: list[str]) -> StringIndex: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str, /) -> bool: ...
    def is_empty(self) -> bool: ...
    def id(self, key: str) -> int | None: ...
    def contains(self, key: str) -> bool: ...
    def key(self, id: int) -> str | None: ...
    def prefix(self, prefix: str) -> list[tuple[str, int]]: ...
    def range(self, lo: str, hi: str) -> list[tuple[str, int]]: ...
    def fuzzy(self, query: str, max_distance: int) -> list[tuple[str, int]]: ...
    def subsequence(self, query: str) -> list[tuple[str, int]]: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> StringIndex: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> StringIndex: ...

@final
class PerfectHashIndex:
    """Minimal-perfect-hash dictionary: fastest exact string->dense id, with persistence."""

    def __new__(cls, items: list[str]) -> PerfectHashIndex: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str, /) -> bool: ...
    def is_empty(self) -> bool: ...
    def id(self, key: str) -> int | None: ...
    def id_unchecked(self, key: str) -> int: ...
    def contains(self, key: str) -> bool: ...
    def key(self, id: int) -> str | None: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> PerfectHashIndex: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> PerfectHashIndex: ...
