#ifndef LEXINDEX_H
#define LEXINDEX_H

/* Generated by cbindgen from src/capi.rs: edit that file, then `cbindgen --config cbindgen.toml src/capi.rs --output include/lexindex.h`. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * The ABI this header describes; `lexindex_abi_version` returns the library's.
 */
#define LEXINDEX_ABI_VERSION 1

/**
 * What `lexindex_index_ids` writes for a key the index does not hold.
 */
#define LEXINDEX_NO_ID 18446744073709551615ull

/**
 * The outcome of a call. Zero is success; every other value but `NOT_FOUND` leaves a message in
 * `lexindex_last_error`.
 */
typedef enum {
  /**
   * The call did what it says.
   */
  LEXINDEX_STATUS_OK = 0,
  /**
   * The key or id is not in the index. An answer, not a failure: the message is untouched.
   */
  LEXINDEX_STATUS_NOT_FOUND = 1,
  /**
   * This kind of index cannot answer the question — see `LexindexKind`.
   */
  LEXINDEX_STATUS_UNSUPPORTED = 2,
  /**
   * A null pointer where one is required, a key that is not UTF-8, or a path that is not.
   */
  LEXINDEX_STATUS_INVALID_ARGUMENT = 3,
  /**
   * The bytes are not a blob this version reads.
   */
  LEXINDEX_STATUS_FORMAT = 4,
  /**
   * The file could not be read or written.
   */
  LEXINDEX_STATUS_IO = 5,
  /**
   * The perfect hash could not be built from these keys.
   */
  LEXINDEX_STATUS_BUILD = 6,
  /**
   * The caller's buffer is too small; the size it needs was written to `len`.
   */
  LEXINDEX_STATUS_BUFFER_TOO_SMALL = 7,
} LexindexStatus;

/**
 * Which of the five indexes a handle holds, smallest first.
 */
typedef enum {
  /**
   * `ClosedHashIndex`: the perfect hash alone. Every key gets an id, membership is not tested,
   * so `contains` is unsupported and `id` of a key outside the set is some other key's.
   */
  LEXINDEX_KIND_CLOSED = 0,
  /**
   * `CompactHashIndex`: the perfect hash and a one-byte fingerprint. No keys stored, so `key`
   * is unsupported; a key outside the set answers as present with probability 2^-8.
   */
  LEXINDEX_KIND_COMPACT = 1,
  /**
   * `DictIndex`: ordered, every key stored, exact both ways; the id is the sorted rank.
   */
  LEXINDEX_KIND_DICT = 2,
  /**
   * `StringIndex`: an fst — ordered, exact both ways; the id is the sorted rank.
   */
  LEXINDEX_KIND_STRING = 3,
  /**
   * `PerfectHashIndex`: exact both ways, unordered.
   */
  LEXINDEX_KIND_PERFECT = 4,
} LexindexKind;

/**
 * An index of any of the five kinds. Opaque: made by `lexindex_index_open`,
 * `lexindex_index_from_bytes` or `lexindex_index_build`, freed by `lexindex_index_free`.
 */
typedef struct LexindexIndex LexindexIndex;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The ABI version this library was built with, to compare with `LEXINDEX_ABI_VERSION`.
 */
uint32_t lexindex_abi_version(void);

/**
 * The crate version as a static NUL-terminated string, `"3.0.0"` and the like.
 */
const char *lexindex_version(void);

/**
 * The message of the most recent failure on this thread, NUL-terminated; empty before any. Valid
 * until the next failure on the same thread.
 */
const char *lexindex_last_error(void);

/**
 * Reads the blob at `path` (NUL-terminated) into a handle of whatever kind it holds, with the
 * validation `load` does in Rust: framing and checksums. Overlay and standalone perfect-hash blobs
 * are `LEXINDEX_STATUS_UNSUPPORTED`.
 *
 * # Safety
 *
 * `path` is a NUL-terminated string and `out` is writable.
 */
LexindexStatus lexindex_index_open(const char *path, LexindexIndex **out);

/**
 * Parses a blob from `len` bytes at `bytes`, copying them: the buffer may go once this returns.
 *
 * # Safety
 *
 * `bytes` points to `len` readable bytes and `out` is writable.
 */
LexindexStatus lexindex_index_from_bytes(const uint8_t *bytes, size_t len, LexindexIndex **out);

/**
 * Builds an index of `kind` from `n` keys, `keys[i]` being `lens[i]` bytes of UTF-8, in any order
 * and with duplicates collapsed. `LEXINDEX_KIND_COMPACT` gets a one-byte fingerprint and
 * `LEXINDEX_KIND_DICT` the default block, which is what `plan` prices them at.
 *
 * # Safety
 *
 * `kind` is one of the enumerators; either `n` is zero or `keys` and `lens` hold `n` entries each
 * and `keys[i]` points to `lens[i]` readable bytes; `out` is writable.
 */
LexindexStatus lexindex_index_build(LexindexKind kind,
                                    const char *const *keys,
                                    const size_t *lens,
                                    size_t n,
                                    LexindexIndex **out);

/**
 * Writes the index to `path` (NUL-terminated) the way `save` does in Rust: to a temporary file
 * beside it, renamed into place once complete.
 *
 * # Safety
 *
 * `index` is a live handle and `path` a NUL-terminated string.
 */
LexindexStatus lexindex_index_save(const LexindexIndex *index, const char *path);

/**
 * Which kind of index the handle holds.
 *
 * # Safety
 *
 * `index` is a live handle; there is no status to report a null one in.
 */
LexindexKind lexindex_index_kind(const LexindexIndex *index);

/**
 * How many keys the index holds.
 *
 * # Safety
 *
 * `index` is a live handle; there is no status to report a null one in.
 */
size_t lexindex_index_len(const LexindexIndex *index);

/**
 * The id of `key` (`key_len` bytes of UTF-8) into `out`, or `LEXINDEX_STATUS_NOT_FOUND`. What
 * "found" means is the kind's: exact for string, dict and perfect; probabilistic for compact,
 * which answers a key outside the set as present with probability 2^-8; every key for closed,
 * the perfect hash alone, which maps a key it never saw to some other key's id.
 *
 * # Safety
 *
 * `index` is a live handle, `key` points to `key_len` readable bytes, `out` is writable.
 */
LexindexStatus lexindex_index_id(const LexindexIndex *index,
                                 const char *key,
                                 size_t key_len,
                                 uint64_t *out);

/**
 * The ids of `n` keys at once, `LEXINDEX_NO_ID` where a key is not held. This is the fast path —
 * the hash indexes prefetch across the batch. A key that is not UTF-8 fails the whole call before
 * anything is written.
 *
 * # Safety
 *
 * `index` is a live handle; either `n` is zero or `keys` and `lens` hold `n` entries each,
 * `keys[i]` points to `lens[i]` readable bytes, and `out` has room for `n` ids.
 */
LexindexStatus lexindex_index_ids(const LexindexIndex *index,
                                  const char *const *keys,
                                  const size_t *lens,
                                  size_t n,
                                  uint64_t *out);

/**
 * Whether `key` is in the index, into `out`: exact for string, dict and perfect, probabilistic for
 * compact (the same 2^-8 as `id`), and `LEXINDEX_STATUS_UNSUPPORTED` for closed, which cannot tell.
 *
 * # Safety
 *
 * `index` is a live handle, `key` points to `key_len` readable bytes, `out` is writable.
 */
LexindexStatus lexindex_index_contains(const LexindexIndex *index,
                                       const char *key,
                                       size_t key_len,
                                       bool *out);

/**
 * The key of `id`, written NUL-terminated into the `cap` bytes at `buf`, its length without the
 * terminator into `len`. `LEXINDEX_STATUS_BUFFER_TOO_SMALL` when `cap < length + 1`, with `len`
 * still set — so `buf = NULL, cap = 0` asks for the size; `NOT_FOUND` for an id the index never
 * gave out; `UNSUPPORTED` for compact and closed, which store no keys.
 *
 * # Safety
 *
 * `index` is a live handle, `buf` points to `cap` writable bytes (or `cap` is zero), `len` is
 * writable.
 */
LexindexStatus lexindex_index_key(const LexindexIndex *index,
                                  uint64_t id,
                                  char *buf,
                                  size_t cap,
                                  size_t *len);

/**
 * Frees a handle; null is a no-op. Every handle is freed exactly once, here.
 *
 * # Safety
 *
 * `index` is null or a handle this library returned that nothing has freed.
 */
void lexindex_index_free(LexindexIndex *index);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LEXINDEX_H */
